trigger:
  - main

stages:
  - template: build-template/build.yml

  - template: deploy-template/deploy.yml
    parameters:
      environmentShortName: dev
      environmentName: Rebuild-Website-Development
      environment: development
      azureWebAppName: dev-rebuild-nantes
      azureWebUrl: https://dev-rebuild-nantes.azurewebsites.net

  - template: deploy-template/deploy.yml
    parameters:
      environmentShortName: staging
      environmentName: Rebuild-Website-Staging
      environment: staging
      azureWebAppName: staging-rebuild-nantes
      azureWebUrl: https://staging-rebuild-nantes.azurewebsites.net
